name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Personal access token (classic) added as the METRICS_TOKEN secret.
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
